### ISSUE TITLE
怎么把greenDao提取到一个单独的module，eg.common module中，主moudle，也就是app中可以正常使用？

### ISSUE THREAD

**Issue by ZQiang94** [stiflerfang/MyBaseCommonModule#1]
如题。

**Comment by ZQiang94** [comment]
452608069 我的qq，有意向可以一起讨论一下 thx、

**Comment by stiflerfang** [comment]
在我的工程里，greendao还没有写完demo，只是先添加进来了，现在在greendao之后又推出了一个objectbox，你可以试着用下这个，号称效率提高了很多。回到你一开始的问题，commnon
moudule一般放的是跟业务无关的代码，就是所有工程能都可以拿来复用的，你的数据库信息都是跟业务强相关的，我个人觉得还是要放在主module会好一些，其次，你现在觉得提取出来觉得有问题，是指哪方面的问题？然后我的主工程里，如果你要看UI上的一些实现，建议你参考module包下的show目录，这个目录下的列表展示才是我推荐的，其他包下的只是一些尝试，没有这个好。

2018-04-13 14:04 GMT+08:00 ZQiang94 <notifications@github.com>:

**Comment by ZQiang94** [comment]
谢谢啦，我现在是在common中提供了接口，然后使用complieOnly仅在编译时候依赖，然后再住module中使用的时候  在依赖一下common，还有greendao；
objectbox正在学习，谢谢。
